title: Marcello Monachesi
description: personal website
collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
theme: jekyll-theme-cayman
github:
  is_project_page: true
google_analytics: UA-147721492-1
