title: Marc
description: personal website
tagline: personal website
email: monachesi.m@live.com

permalink: pretty

collections:
  products:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

paginate: 5
paginate_path: "/blog/page:num"

google_analytics: G-DXBMYDSLGL

# TODO: migrate to v1 https://www.csrhymes.com/bulma-clean-theme/docs/getting-started/upgrading-to-v1/
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0 

footer_menu: footer_menu

cookie_policy: /cookie-policy/
