title: Marc
description: personal website
tagline: my personal website
email: monachesi.m@live.com

permalink: pretty

collections:
  authors:
    output: true
  products:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

paginate: 5
paginate_path: "/blog/page:num"

google_analytics: UA-147721492-1

remote_theme: chrisrhymes/bulma-clean-theme

footer_menu: footer_menu
