title: Marcello Monachesi
description: personal website
collections:
  authors:
    output: true

paginate: 5
paginate_path: "/blog/page:num"
#theme: bulma-clean-theme
#github:
#  is_project_page: true
google_analytics: UA-147721492-1
remote_theme: chrisrhymes/bulma-clean-theme
