title: Marc
description: personal website
tagline: personal website
email: monachesi.m@live.com

permalink: pretty

collections:
  products:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

paginate: 5
paginate_path: "/blog/page:num"
repository: marcello-dev/marcello-dev.github.io

google_analytics: G-DXBMYDSLGL

remote_theme: chrisrhymes/bulma-clean-theme

footer_menu: footer_menu

cookie_policy: /cookie-policy/
